### ISSUE TITLE
Decision tree for deciding whether to set denoise.counts = TRUE

### ISSUE THREAD

**Issue by malisas** [niaid/dsb#14]
Hi, thanks for providing dsb!

I am analyzing an experiment which did not use isotype controls. I went through your vignette in order to figure out whether I should be setting `denoise.counts = TRUE`. I created the decision tree below to help me (and potentially others) decide, and I would like feedback on whether it is accurate. Thank you. (I can also share/edit the lucidchart if you like.)

![dsb denoise counts decision tree](https://user-images.githubusercontent.com/16787492/104292621-e7af6000-5471-11eb-9ac7-828d210b1e48.png)

* * * * * * * * * * * * * * *

To follow-up for my specific experiment:  

I am at outcome **(B)** because µ1 and µ2 are significantly correlated for my experiment and we did not include isotype controls.   
This means that I was able to use dsb to remove protein-specific background noise by using the empty droplets, but the technical cell-to-cell variation is still present in my data.  

In your experience, how appropriate is this partially-denoised data for downstream applications such as 1) gating (as in the flow cytometry context) or 2) clustering or  3) differential expression analysis (between clusters or between sets of patients)? Or is that something that will vary from experiment-to-experiment and depends on the ratio of biological signal:technical noise? Basically, I am wondering how usable our data are.  

Your answer will also help inform whether we include isotype controls in future experiments.  
(Edit: Your answer [here](https://github.com/niaid/dsb/issues/7#issuecomment-622379938) addresses this question actually)

As a sort of experiment, I've plotted CD4 vs CD8 plots below using ADT data collected from a subset of T cells. Note the subset of T cells in our experiment are primarily CD8+. I've plotted the raw and dsb-transformed data side-by-side.  

Interestingly, the third panel (where I used `denoise.counts = TRUE` despite µ1 and µ2 being significantly correlated) is most similar to what we see using flow cytometry<sup>*</sup>. The third panel also doesn't have those artificial vertical lines, which seems like a plus.  
However, according to the dsb recommendations, it seems as though I should probably proceed with the data from panel 2 (`denoise.counts = FALSE`) so I don't lose biological signal. It's just a shame the data can't be cleaned up any further. If you have further thoughts or advice on this, I am interested. :)

<sup>*</sup> though I understand that flow data may not necessarily be a “gold standard” here because it has its own set of problems like fluorescent spillover

![plot_zoom_png](https://user-images.githubusercontent.com/16787492/104290826-a9b13c80-546f-11eb-8225-69886d42d850.png)

Thank you so much for your feedback and advice.

**Comment by MattPM** [comment]
Hi @malisas , Thanks very much for making the helpful flow chart! It is accurate, if you don't mind, pls do send to mulemp AT nih.gov, I might want to slightly adjust and add it to the package readme / FAQ.

I think overall your data looks really good. You could certainly use the data in the center plot (denoise.counts = FALSE version) for clustering, gating etc. Although the denoise.counts = TRUE version removes the "picket fencing" induced by log transformation which helps with gating, your populations are decently separated and you should be able to draw gates on the denoise.counts = FALSE data.  To be conservative, you could start with the denoise.counts = FALSE version and cluster based on protein as shown in the vignette. If the average protein levels of some of the resulting clusters look identical in their distribution but seem to only differ in global protein levels (so globally "bright" and "dim" versions of the same population), I would then try the version with denoise.counts = TRUE. Those global dim/bright populations should merge together. 

I am wondering what was the strength of the correlation between µ1 and µ2 (the effect size like pearson or spearman rho)? If the coefficient is low (even if p val is low), it may not be a big problem in your data.  We aimed to be conservative on recommendations since we can't *guarantee* denoise.counts = TRUE would only remove noise as opposed to biological signal without isotype controls. Because of that, to answer your other question, we would definitely recommend adding isotype controls in future experiments (although I emphasize your current data definitely looks quite good and are useable for sure). The denoise.counts argument is defining and regressing out the "technical component" for each cell and without isotype controls, the technical component is just µ1, the mean of each cell's background protein. µ1 alone *may* have some biological signal (depending on the strength of correlation of µ1 with biological factors like µ2) so by default, we recommend being cautious. Based on how the technical component is calculated, adding isotype controls "anchors" the component of µ1 that is correlated with noise as opposed to biological signal, so those controls help make it less likely to remove biological signal.

**Comment by malisas** [comment]
Thank you for the advice! 

For the data I showed, for µ1 and µ2, pearson's cor = 0.7723826 and p-value < 2.2e-16.  
This seems like a strong correlation to me (and therefore supports the use of the `denoise.counts = FALSE` version). Though from your comment, it sounds like I may still be able to use (and potentially prefer to use) the `denoise.counts = TRUE` version, depending on how much biological signal is preserved. (And at least for distinguishing CD4 and CD8a subpopulations, the signal seems to be preserved). So it seems the biological signal can survive the denoising even if some of it gets "regressed" out. I suppose a separate question is whether potential differences between Patient Group A and Patient Group B (the primary experimental question) are preserved if I use `denoise.counts = TRUE` on these data. Anyway, I will try out clustering using both versions of the data, like you suggested, and see which looks better. Thanks again and take care!
