### ISSUE TITLE
DSB normalising with artificial (zero) background

### ISSUE THREAD

**Issue by jkniffka** [niaid/dsb#19]
Hi @MattPM ,

We have 5 CITEseq datasets and for these we have normalized the ADT counts with DSB. In a second step we integrate all data sets into each other. Now we would like to insert an ABseq dataset. Unfortunately there is no information about the empty droplets. Due to the integration method we would like to use a uniform preprocessing as far as possible.
We wonder if there is a way to normalize the ABseq data with DSB? (For example: Could we create an artificial empty droplet matrix and just fill it with 0 values. I.e. we want to simulate that there is no background).

Thank you in advance! :)

**Comment by MattPM** [comment]
Hi, 

Your idea to integrate datasets sounds cool; your question is a bit outside the scope of the dsb package and abseq is not a droplet single cell method so it is not something we dissected out with experiments and modeling in the preprint.  I'm not endorsing the ideas below as they are based on assumptions I have not validated for abseq data, but these are just some ideas to help you get started.  

The first thing I would try is just converting the dsb normalized values and whatever you are using for abseq into z scores across cells in each experiment.

If you want to try something more like dsb on the abseq data, you could play with some ideas below.  

First, we can't use a matrix of 0 as background because internally dsb divides by values calculated on the empty drop matrix and we can't divide by 0. More importantly I don't think we can just assume there is no background noise in abseq data. When  you use that lever device to partition the cell mixture across the microwells, it is possible the same ambient antibody that gets encapsulated in drops in CITE-seq data, could be partitioned into those wells (that is just an idea). If the data was perfect and only signal and no noise for each cell, we'd expect there to be a perfect background population for each protein with cells having 0 counts and a log gaussian range of positive counts on the stained cells. 

I downloaded this public data: 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4005486

```
library(tidyverse)
test = read.csv(file = "GSM4005486_Combined_PBMC_AbSeq_1_DBEC_MolsPerCell_with_SampleTag.csv"), sep = ",")
# get abseq index 
cite = test[ ,c(1,71:136)]
cite = cite %>% column_to_rownames("Cell_Index") %>% select(contains("pAb"))
# calculate fraction of cells with non zero protein raw reads.
nnz = apply(cite, 2, function(x){Matrix::nnzero(x)})
fnz = data.frame(fraction_nonzero = nnz / dim(cite)[1]) %>% 
  rownames_to_column("prot") 
ggplot(fnz, aes(x = prot, y = fraction_nonzero)) + geom_point() + coord_flip()
```

<img width="520" alt="abseq_fracnzero" src="https://user-images.githubusercontent.com/15280712/113533511-11bd7d80-959c-11eb-8096-be384241aa92.png">

Basically all of the proteins are non zero in every cell. That at least initally suggests to me that there is background noise. 

One thing you could therefore try is making the assumption that each protein can be captured by a Gaussian mixture fit to each protein to extract out the expected noise in the form of the background mean and vairance. This is distinct from the Gaussian mixture we use in dsb on *each cell*.  

```
# remove the protein that did not work in the experiment
cite = cite[, setdiff(colnames(cite),'CD184.CXCR4.AHS0060.pAbO')]

# log counts  
adt_log = log(cite + 1)

# fit gaussian mixture to each protein
prot_model = apply(adt_log, 2, function(x) { mclust::Mclust(x, G=2, warn = TRUE , verbose = TRUE) } )

# background mean and variance 
mu1 = lapply(prot_model, function(x) x$parameters$mean[1]) %>% unlist 
pvar1 = lapply(prot_model, function(x) x$parameters$variance$sigmasq[1]) %>% unlist 

# background correction  
norm_adt = apply(adt_log, 2, function(x) (x - mu1)/pvar1) %>% as.data.frame()

# visualize
dtidy = d %>% gather(prot, pseudo_dsb, CD103.ITGAE.AHS0001.pAbO:CD4.CD4.AHS0032.pAbO)
ggplot(dtidy, aes(x = pseudo_dsb, y = prot)) + ggridges::geom_density_ridges()
```
Values are in a similar range as dsb values and the background population is centered at zero. You cold play around with something similar to this on your data. Again, while there are some similarities in sequencing DNA barcoded antibodies, we did not model or experimentally derive the sources of noise for non-droplet data like abseq and this is just a first pass idea to get you started  Good luck w your analyis! 

<img width="441" alt="pseudo_dsb_abseq" src="https://user-images.githubusercontent.com/15280712/113533690-85f82100-959c-11eb-897a-4cad8b8d0d0a.png">
