### ISSUE TITLE
CiteSeqCount on empty droplet whitelist

### ISSUE THREAD

**Issue by kristiangu** [niaid/dsb#29]
Hi, 

I am trying perform dsb normalisation on my ADTs. However, I am encountering an issue when it comes to perform CiteSeqCount on the whitelists of the empty droplets (excluded filtered barcodes from CellRanger). Basically, the analysis is stuck at testing cell barcode collapsing thresholds.
This happens on samples that have 2.5 to 3 million barcodes in their empty droplets.

Any suggestion? I may be doing something wrong.

Thanks

**Comment by MattPM** [comment]
Hi, so this a bit more of a CITEseq-count question upstream of dsb but I'm happy to help out. 

Can you display the command you used for CiteSeqcount? 

So I understand, you ran Cell Ranger on the RNA data, from that used the filtered output to get cell containing droplet barcodes, then tried to run CiteSeqCount using a whitelist consisting of what you think are empty drops only without those cells? If so, I don't think that will work–the simplest way to use CITE-seq count is to not use a whitelist of barcodes: just specify a high number for the `-cells` parameter: try an order of magnitude higher than the number of droplets you expected to recover (or 10 x the number of cells estimated by Cell Ranger). You don't need to provide a whitelist. Basically tell CiteSeqCount that you expect a ton of cells and it will align the top ranked barcodes retaining all the cells and the major background signal. https://hoohm.github.io/CITE-seq-Count/Running-the-script/ -- see the `-cells` argument. 

Also, what antibodies are you using? You may be able to align your ADTs with Cell Ranger which would be simpler (that is basically shown in the vignette).

**Comment by kristiangu** [comment]
Sorry for the late response.
You are right. I have been trying to run CiteSeqCount on a whitelist of barcodes which I expect to be empty.
The code I used is the following:
`CITE-seq-Count -R1 Sample_combined_R1_001.fastq.gz -R2 Sample_combined_R2_001.fastq.gz  -t Tags.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells Number_of_cells_in_whitelist -wl Empty_whitelist_Sample.csv -T 96`
For this experiment I used BioLegend TotalSeq-A antibodies.
Given that the number of 'good' cells range between 3-10k, should I just set -cells to around 1M (10-100x the number of filtered barcodes)?
Thanks

**Comment by MattPM** [comment]
@gt7901b The function should not take that much longer with different sized background matrix. The warning you're reporting sounds like your matrices are not the same dimensions--check if your background and cell matrix have the same number of rows? (same number of proteins in the same positions) 
`all.equal(nrow(pos_adt_matrix), nrow(negative_mtx_rawprot))`

^That is important so you want to look into what is causing that error, if you can't find it I can help if you send your data. 

The range you're reporting ~0-20 is typical for dsb values.

Overall, the hybrid approach you're describing sounds better to me. 

FYI Re: "When I use HTODemux negative as empty droplets from filtered feature barcode matrix"
This isn't listed in any of Seurat's tutorials, but if you run HTODemux on only the filtered barcodes, these are highly enriched for cells only. The function can improve somewhat if you use more drops (i.e. the top 50-80k barcodes based on total protein counts for each 10X lane) because the function is trying to find empty / negative drops with low HTO staining (by setting K = 1+ nHTO in the k medoids function). If you only run HTODemux on what CellRanger thinks is a cell, then you will have a tiny number of negatives detected by HTODemux (like the 1000 you are reporting--this is too few negatives I think). However, what you did with your hybrid approach is definitely fine, all you're trying to do is get the major background population which should be really clear if you plot the total log protein counts across all droplets (from the raw matrix) with non-zero ADT counts as in the tutorial.

**Comment by gt7901b** [comment]
many thanks, @MattPM . “longer object length is not a multiple of shorter object length”  is caused by difference of one Ab. Because one of the negative control Ab has zero counts in negative_mtx_rawprot (there are two negative ctrl Abs in all), I remove that Ab from negative_mtx_rawprot. despite warning, the dsb still finished normalization. Is that fine?
