### ISSUE TITLE
Question: Workflow using HTOdemux

### ISSUE THREAD

**Issue by m3lorra** [niaid/dsb#30]
Hello, 

First of all, thanks a lot for this package and all the documentation that you have attached with it, it have helped me a lot. 

However, I still have few questions and I would like to know your thoughts. 

My data includes ADTs (24 + 1 isotype ctrl) and Hashtags (6). We decided to use only one isotype control because is the most abundant in our panel (and to make it more cost/effective(?)). 
So here, since I don't have a control for all the abs do you still advise to use the data from that one isotype? 

Since I have the data from the Hashtags, I've been trying to run HTOdemux in the raw data but it get stuck at the end (when all Cutoff have been set) so I have to kill it (I also tried running it overnight, but it doesn't finish). 

Therefore, I started using HTOdemux in the "filtered" data and runs smoothly. But I realized that when I use HTOdemux after "NormalizeData" I get more "Singlets" (11274 out of 13190 total cells  vs 9365 out of 13190 total cells). 
I think that using the "Negative" cells from Normalized HTO works better, but I wanted to know why you wouldn't normalize prior HTOdemux?
Then, I add the cells detected as Negative from HTOdemux to the "background_drops" that I selected using your pipeline (`background_drops = md[md$prot_size > 1.5 & md$prot_size < 2.5 & md$ngene < 100, ]$bc`) and I use this matrix of Negative + Background to run with "DSBNormalizeProtein". Then, the normalized proteins data are added to my Seurat object that was demultiplexed. Does it makes sense this approach?

Thanks a lot

Stephania

**Comment by MattPM** [comment]
Hi @m3lorra 

>So here, since I don't have a control for all the abs do you still advise to use the data from that one isotype?

Yes, the way the dsb technical component works with isotype controls does not depend on matching isotypes to each corresponding fc region of the phenotyping antibodies. 

All isotypes (in your case the single isotype) are combined with the background mean learned by dsb in step II into a noise variable matrix. dsb finds the eigenvector through those variables and the loading score (PC1 score) is then used as the technical component and regressed out of the log transformed ambient background noise corrected values. In the case of 1 isotype control, you can imagine a 2d scatterplot with the isotype value on one axis and the cell's background mean on the other axis. The dsb technical component will reflect each cells position along the line of maximal variance (the eigenvector) through those 2 variables. Adding the isotype control will help 'anchor' the variation in the background mean toward the technical, non biological variation. In experiments with one isotype control, dsb has worked well for us. I would recommend using the recommended default setting `denoise.counts = TRUE`, `use.isotype.control = TRUE`.  


>Does it makes sense this approach?

The answer to your questions about defining background when using Hashing antibodies depend in part on how many cells you loaded / expect to recover and how you set the Cell Ranger parameter `expected-cells`

If you kept this parameter at the default, (3000) then the cell ranger output filtered matrix is more likely to contain mostly cell-containing droplets. If you use only these barcodes for HTODemux, then the barcodes that HTODemux defines as "Negative" are more likely to be cells that had poor quality HTO staining, as opposed to empty droplets which would better reflect the ambient component of background noise. Please see here: 
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count#args

Ideally this should be set to the number of doublets + singlets you expect to recover based on how many cells were loaded per lane. However, if you are going to use HTODemux, I wouldn't bother much with the filtered output from cell ranger since the barcode rank algorithm might be pretty far off. 

How many droplets did you use as input to HTODemux? When you ran HTOdemux on the raw data, did you include ALL the droplets from the Cell Ranger raw output? 

If yes, that is probably why the HTODemux algorithm is not converging. I would recommend you use only the major background peak and not all the background cells since the full raw output contains every theoretical barcode but only some were captured (and thus contain information about the ambient component of noise) in the experiment. That is why (I think) HTODemux is not converging. I would plot a histogram of the sum of ADT counts (`Matrix::colSums(x)`) in the raw output HTO and ADT matrix and remove all the droplets that fall below the major background peak. As in the tutorial, the major backgorund peak should be clear and it will contain likely 5-10X the number of cells you expected to recover.  Another way to pre filter the data before you run HTODemux is to use try setting the `min.gene` argument to perhaps 10 or 20 when you run Seurat::CreateSeuratObject(). That will include only cells with some mRNA reads. 

As for the number of singlets doublets and negatives returned by HTODemux, this is outside the scope of dsb, however some guidance: The settings of HTODemux will alter the number of singlets returned; this is a good function to get you the main droplets captured in the experiment but you will still need to eliminate poor quality cells an additional doublets that appear in downstream analysis so I would set the algorithm so that you retain a good number of singlets in line with what you expected (ok to be liberal here) then remove poor quality cells with downstream QC on number of reads, MT gene content etc. You can also try the multiseq approach that is now included in Seurat: `Seurat::MULTIseqDemux()`. 

Please let us know if you have further questions.

**Comment by m3lorra** [comment]
Thank you for your response @MattPM ! 

> Yes, the way the dsb technical component works with isotype controls does not depend on matching isotypes to each corresponding fc region of the phenotyping antibodies.

- Great, I'll keep using the isotype that I have as control. Thanks! 

> The answer to your questions about defining background when using Hashing antibodies depend in part on how many cells you loaded / expect to recover and how you set the Cell Ranger parameter expected-cells

- About the expected cells parameter, I set it at 10K cells and I got around 13K cells identified by cellranger. I did a test setting it at 18K cells (which would be the real number, since I loaded 36K cells and accounting for 50% loss) and I got about the same result. 

>  How many droplets did you use as input to HTODemux? When you ran HTOdemux on the raw data, did you include ALL the droplets from the Cell Ranger raw output?

You are right. I was using the whole "raw" matrix (without filtering) when I was trying to run it. 
I did some tests changing the input of the "empty_drop_matrix". 
Test 1: Background defined by the histogram plots using `background_drops = md[md$prot_size > 1.5 & md$prot_size < 2.5 & md$ngene < 100, ]$bc
` nºcells: 20
Test 2: Background defined by HTOdemux as "negative" cell. nºcells: 74
Test 3: Mix of test 1 + test 2 = 94 cells 

The input in "cell_protein_matrix" is the same for all the tests: a matrix of cells after QC (based in library size, mt%, etc) and only singlets. 

These are the results that I got: 
Another detail that maybe can help to find the best approach is that I used CD117 to sort the cells. CD117, in this case, is a TotalSeq-A conjugated to Alexa Fluor fluorochrome and we sorted all CD117+. 
 
[00.QC_noNegativeBackground_filt1.5_2.5_10Jan.pdf](https://github.com/niaid/dsb/files/7838940/00.QC_noNegativeBackground_filt1.5_2.5_10Jan.pdf)

[00.QC_OnlyNegativeBackground_NormHTOdemux_10Jan.pdf](https://github.com/niaid/dsb/files/7838941/00.QC_OnlyNegativeBackground_NormHTOdemux_10Jan.pdf)

[00.QC_WithNegativeBackground_filt1.5_2.5_10Jan.pdf](https://github.com/niaid/dsb/files/7838942/00.QC_WithNegativeBackground_filt1.5_2.5_10Jan.pdf)

I think the first plot shows better CD117 expression. Please correct me if I'm wrong.

Thanks a lot

**Comment by MattPM** [comment]
The CD117 is a good control since you sorted cells and it looks like the average CD117 after normalization is ~11 so the average across cells is around 11 standard deviations above the mean in the background. 

There are some (likely very few) high magnitude outliers in your matrix that is why the scale goes out so far, you can get rid of those by setting `quantile.clip = TRUE`. Overall, normalization looks like it worked well with the manually defined background (using the histogram cutoffs) so I would stick with that. 

As far as the number of negative drops you are getting with HTODemux (74), that is too few cells to use as the background matrix; those are more likely very low quality cells with poor staining–they will still likely work as a background estimate but it is not the intended use of dsb which is trying to correct for ambient antibody in the step using background. You have 60K background drops when you use the histogram method to get the major background peak–that is good–more in line with what we expect to see for background.  If you only got 74 negative cells after HTODemux that means you had mostly singlets and doublets in the matrix with most of the 60K background drops eliminated already.  I should make this part of the documentation more clear. What I meant above was you can read in the major background peak + the cells then run HTODemux because the function will have more drops to estimate the negative fraction from. If you then set a relatively high quantile parameter in HTODemux, you will end up with a lot of singlets–these still need to be QCd but this method can help to 'rescue' singlets that sometimes get lost when people use the default filtered output from cell ranger with HTO data + superloading.
