### ISSUE TITLE
longer object length is not a multiple of shorter object length

### ISSUE THREAD

**Issue by dtatarak** [niaid/dsb#31]
I'm trying to run DSBNormalizeProtein on a REAP-seq data set. I read in the RNA and protein expression matrices with the `Read10X` function from Seurat, then proceeded to make a vector of cells and empty droplets. `cells` and `empty` respectively.

I split out the empty droplet and cell-containing matrices below:
```
raw_prot_mat <- object_raw$`Antibody Capture`  %>% as.matrix()
empty_prot_mat <- raw_prot_mat[,empty] %>% as.matrix()
cell_prot_mat <- raw_prot_mat[,cells] %>% as.matrix()

```

I then fed these into the `DSBNormalizeProtein` function. 

```
test <-DSBNormalizeProtein(cell_protein_matrix = cell_prot_mat, 
                    empty_drop_matrix = empty_prot_mat,
                    denoise.counts = F,
                    use.isotype.control = FALSE)
```

It outputs the following error message: `"longer object length is not a multiple of shorter object length"`.

I haven't seen this particular error reported by anyone else, yet so I thought I would ask: any idea what is causing this error? Very possible I'm missing something simple/fundamental. Thanks!

**Comment by MattPM** [comment]
Hi, quick question: can tell me what version of dsb you are using? (`sessionInfo()` will show it). 

This is a base R error message. You will see the same thing if you try to do some operations on vectors that are not the same length, for example: `c(1,2) - c(1, 2, 3)`

Based on how dsb works, that could be caused by different proteins in the empty and cell matrix. 
A quick check: 
`isTRUE(all.equal( cell_prot_mat ,  empty_prot_mat))`
Is this `FALSE`? If so, check:
`setdiff(cell_prot_mat ,  empty_prot_mat) ; setdiff(empty_prot_mat, cell_prot_mat) ` 

That should tell you if there are different proteins. The same proteins must be in both matrices. 

You should get a more informative error message if that was the case with the most up to date version of dsb (0.3.0) which is why I was wondering about version. 

Happy to help further.

**Comment by dtatarak** [comment]
Thanks for the quick reply! I was using version 0.10, so I updated to 0.3.0. 

Your test `isTRUE(all.equal( cell_prot_mat , empty_prot_mat))` indeed returns `FALSE`.

You were right. There was a discrepancy in the number of rows between the matrices. Problem solved! Thanks very much!

**Comment by dtatarak** [comment]
One thing though: After updating to v0.3.0 I still did not get a more descriptive error message. Just FYI.
